modLoader="javafml"
loaderVersion="[40,)"
license="All rights reserved"

[[mods]]

modId="linkchest"

version="${file.jarVersion}"

displayName="The Create link chest addon"

description=''

[[dependencies.linkchest]]
modId="forge"
mandatory=true
versionRange="[43,)"
ordering="NONE"
side="BOTH"

[[dependencies.linkchest]]
modId="minecraft"
mandatory=true
versionRange="[1.19.2,1.20)"
ordering="NONE"
side="BOTH"

[[dependencies.linkchest]]
modId="create"
mandatory=true
versionRange="[0.5.0.i,)"
ordering="AFTER"
side="BOTH"
